---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: pod-monitoring
  namespace: pod-monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-monitoring
  namespace: pod-monitoring